import {activationStatuses,assignmentStatuses,operationsAPI,shiftPayload,assignmentPayload,findScheduleConflict,coverage} from './operations-data.mjs';

const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const normalize=value=>String(value??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const localValue=value=>{if(!value)return'';const date=new Date(value),pad=n=>String(n).padStart(2,'0');return `${date.getFullYear()}-${pad(date.getMonth()+1)}-${pad(date.getDate())}T${pad(date.getHours())}:${pad(date.getMinutes())}`;};
const shortDate=value=>new Intl.DateTimeFormat('es-VE',{weekday:'short',day:'2-digit',month:'short',hour:'numeric',minute:'2-digit'}).format(new Date(value));
const money=(cents,currency)=>cents==null?'Por definir':new Intl.NumberFormat('es-VE',{style:'currency',currency}).format(cents/100);
const field=(label,name,value='',extra='')=>`<label>${label}<input name="${name}" value="${esc(value)}" ${extra}></label>`;

export async function mountOperations({agency,client,shell,active,notice}){
 const api=operationsAPI(client);shell('<div class="loading-skeleton" role="status" aria-label="Cargando activaciones"><span></span><span></span><span></span></div>','Activaciones');
 const data=await api.load(agency);if(!active())return null;
 let dirty=false,busy=false,query='',status='open',current=null;
 const controller={dirty:()=>dirty,pending:()=>busy};
 const activityShifts=id=>data.shifts.filter(row=>row.activation_id===id);
 const activityAssignments=id=>{const ids=new Set(activityShifts(id).map(row=>row.id));return data.assignments.filter(row=>ids.has(row.shift_id));};
 const brandsFor=id=>data.links.filter(row=>row.activation_id===id).map(row=>data.brands.find(brand=>brand.id===row.brand_id)).filter(Boolean);
 const refresh=async id=>{const fresh=await api.load(agency);if(!active())return;Object.assign(data,fresh);current=id?data.activations.find(row=>row.id===id):null;};

 function list(){
  current=null;dirty=false;
  shell(`<section class="operations"><div class="operations-heading"><div><span class="eyebrow">Operación de campo</span><h2>Activaciones</h2><p class="muted">Organiza cliente, marcas, turnos y promotoras desde un solo lugar.</p></div><button class="primary" data-op="new">Nueva activación</button></div><div class="operations-tools"><label>Buscar<input id="operations-search" type="search" placeholder="Actividad, cliente, marca o ciudad" value="${esc(query)}"></label><label>Mostrar<select id="operations-status"><option value="open">En curso</option><option value="all">Todas</option>${Object.entries(activationStatuses).map(([value,label])=>`<option value="${value}">${label}</option>`).join('')}</select></label></div><p id="operations-count" class="hint" role="status"></p><div id="operations-list"></div></section>`,'Activaciones');
  const section=document.querySelector('.operations');section.querySelector('#operations-status').value=status;
  section.querySelector('#operations-search').oninput=event=>{query=event.target.value;renderRows();};
  section.querySelector('#operations-status').onchange=event=>{status=event.target.value;renderRows();};
  section.onclick=event=>{const button=event.target.closest('[data-op]');if(!button)return;if(button.dataset.op==='new')editActivation(null);if(button.dataset.op==='open')detail(data.activations.find(row=>row.id===button.dataset.id));};
  renderRows();
 }
 function renderRows(){
  const open=new Set(['draft','published']);
  const rows=data.activations.filter(row=>(status==='all'||(status==='open'?open.has(row.status):row.status===status))&&normalize([row.name,row.city,row.venue_name,data.clients.find(client=>client.id===row.client_id)?.name,...brandsFor(row.id).map(brand=>brand.name)].join(' ')).includes(normalize(query))).sort((a,b)=>{
   const first=activityShifts(a.id)[0]?.starts_at||'9999',second=activityShifts(b.id)[0]?.starts_at||'9999';return first.localeCompare(second);
  });
  document.querySelector('#operations-count').textContent=`${rows.length} de ${data.activations.length} activaciones`;
  document.querySelector('#operations-list').innerHTML=rows.length?`<div class="activation-list">${rows.map(row=>{
   const shifts=activityShifts(row.id),assignments=activityAssignments(row.id),required=shifts.reduce((sum,item)=>sum+item.required_people,0),assigned=assignments.filter(item=>['pending','accepted','completed'].includes(item.status)).length;
   const clientName=data.clients.find(client=>client.id===row.client_id)?.name||'Cliente por definir';
   return `<button class="activation-row" data-op="open" data-id="${row.id}"><span class="activation-date">${shifts[0]?shortDate(shifts[0].starts_at).split(',')[0]:'Sin fecha'}</span><span class="activation-main"><strong>${esc(row.name)}</strong><small>${esc(clientName)} · ${esc(row.city)}${row.venue_name?' · '+esc(row.venue_name):''}</small><span class="tag-line">${brandsFor(row.id).map(brand=>`<span class="tag">${esc(brand.name)}</span>`).join('')||'<span class="tag muted">Sin marcas</span>'}</span></span><span class="activation-coverage"><span class="badge status-${row.status}">${activationStatuses[row.status]}</span><small>${shifts.length} ${shifts.length===1?'turno':'turnos'} · ${assigned}/${required} cupos</small></span><span aria-hidden="true">→</span></button>`;
  }).join('')}</div>`:`<div class="directory-empty"><h3>${data.activations.length?'No hay coincidencias':'Crea tu primera activación'}</h3><p>${data.activations.length?'Prueba otro filtro o búsqueda.':'Añade el trabajo, sus marcas y luego organiza los turnos del equipo.'}</p></div>`;
 }
 function activationForm(row){
  const selected=new Set(brandsFor(row?.id).map(brand=>brand.id));
  return `<form id="activation-form" class="operations-form"><div class="form-section"><h3>Información principal</h3><div class="form-grid">${field('Nombre de la activación *','name',row?.name,'required minlength="2" maxlength="120"')}${field('Ciudad *','city',row?.city,'required maxlength="120"')}<label>Cliente<select name="client_id"><option value="">Por definir</option>${data.clients.filter(item=>!item.archived||item.id===row?.client_id).map(item=>`<option value="${item.id}" ${item.id===row?.client_id?'selected':''}>${esc(item.name)}</option>`).join('')}</select></label><label>Estado<select name="status">${Object.entries(activationStatuses).map(([value,label])=>`<option value="${value}" ${value===(row?.status||'draft')?'selected':''}>${label}</option>`).join('')}</select></label>${field('Lugar o punto de venta','venue_name',row?.venue_name,'maxlength="160" placeholder="Ej. C.C. Sambil"')}${field('Dirección','address',row?.address,'maxlength="300"')}</div></div><fieldset class="brand-selector"><legend>Marcas de esta actividad</legend><div class="check-grid">${data.brands.filter(item=>!item.archived||selected.has(item.id)).map(item=>`<label class="check-option"><input type="checkbox" name="brand_ids" value="${item.id}" ${selected.has(item.id)?'checked':''}>${esc(item.name)}</label>`).join('')||'<small>Añade marcas en el directorio para seleccionarlas aquí.</small>'}</div><small>Puedes incluir varias marcas en una expo o actividad grande.</small></fieldset><label>Notas operativas<textarea name="notes" maxlength="1000" rows="4" placeholder="Montaje, uniforme, materiales o indicaciones importantes">${esc(row?.notes)}</textarea></label><div class="actions"><button class="primary" type="submit">${row?'Guardar cambios':'Crear y añadir turnos'}</button><button type="button" data-op="cancel">Cancelar</button></div></form>`;
 }
 function editActivation(row){
  current=row;dirty=false;shell(`<section class="operations detail"><button data-op="back">← Volver a activaciones</button><div class="operations-heading"><div><span class="eyebrow">${row?'Configuración':'Nueva activación'}</span><h2>${row?'Editar activación':'Prepara el trabajo'}</h2><p class="muted">Define los datos principales y las marcas involucradas.</p></div></div>${activationForm(row)}</section>`,'Activaciones');bindActivationForm(row);
 }
 function bindActivationForm(row){
  const form=document.querySelector('#activation-form');form.oninput=()=>dirty=true;form.onchange=()=>dirty=true;
  document.querySelector('.operations').onclick=async event=>{const button=event.target.closest('[data-op]');if(!button)return;if(['back','cancel'].includes(button.dataset.op)){if(dirty&&!window.confirm('¿Descartar los cambios sin guardar?'))return;list();}};
  form.onsubmit=async event=>{event.preventDefault();if(busy||!active())return;busy=true;const controls=[...form.elements];controls.forEach(control=>control.disabled=true);
   try{const values=Object.fromEntries(new FormData(form));values.brand_ids=new FormData(form).getAll('brand_ids');const saved=await api.saveActivation(agency,row?.id||crypto.randomUUID(),row?.revision??null,values);await refresh(saved.id);dirty=false;detail(current);notice(row?'Activación actualizada.':'Activación creada. Ahora añade sus turnos.');}
   catch(error){notice(error.message||'No se pudo guardar. Tus cambios siguen aquí.',true);}finally{busy=false;controls.forEach(control=>control.disabled=false);}
  };form.elements.name.focus();
 }
 function detail(row){
  current=row;dirty=false;const shifts=activityShifts(row.id);
  shell(`<section class="operations detail"><button data-op="back">← Volver a activaciones</button><div class="detail-header"><div><span class="eyebrow">${esc(data.clients.find(client=>client.id===row.client_id)?.name||'Cliente por definir')}</span><h2>${esc(row.name)}</h2><p class="muted">${esc(row.city)}${row.venue_name?' · '+esc(row.venue_name):''}</p><div class="tag-line">${brandsFor(row.id).map(brand=>`<span class="tag">${esc(brand.name)}</span>`).join('')||'<span class="tag muted">Sin marcas</span>'}</div></div><div class="actions"><span class="badge status-${row.status}">${activationStatuses[row.status]}</span><button data-op="edit">Editar datos</button></div></div><div class="section-heading"><div><h3>Turnos y equipo</h3><p class="muted">Cada turno controla sus cupos y evita cruces de horario.</p></div><button class="primary" data-op="new-shift">Añadir turno</button></div><div class="shift-list">${shifts.length?shifts.map(shiftCard).join(''):'<div class="directory-empty"><h3>Aún no hay turnos</h3><p>Añade la fecha, el horario y cuántas promotoras necesitas.</p></div>'}</div></section>`,'Activaciones');
  document.querySelector('.operations').onclick=event=>{const button=event.target.closest('[data-op]');if(!button)return;const shift=data.shifts.find(item=>item.id===button.dataset.id);if(button.dataset.op==='back')list();if(button.dataset.op==='edit')editActivation(row);if(button.dataset.op==='new-shift')editShift(null);if(button.dataset.op==='edit-shift')editShift(shift);if(button.dataset.op==='assign')editAssignment(shift,null);if(button.dataset.op==='edit-assignment')editAssignment(shift,data.assignments.find(item=>item.id===button.dataset.assignment));};
 }
 function shiftCard(shift){
  const assignments=data.assignments.filter(item=>item.shift_id===shift.id),count=coverage(shift,data.assignments);
  return `<article class="shift"><div class="shift-head"><div><strong>${shortDate(shift.starts_at)} — ${new Intl.DateTimeFormat('es-VE',{hour:'numeric',minute:'2-digit'}).format(new Date(shift.ends_at))}</strong><small>${count.assigned} de ${count.required} cupos ${count.complete?'cubiertos':'asignados'}</small></div><div class="actions"><span class="badge ${count.complete?'coverage-ok':'coverage-open'}">${count.complete?'Completo':`${count.required-count.assigned} por cubrir`}</span><button data-op="edit-shift" data-id="${shift.id}">Editar</button><button data-op="assign" data-id="${shift.id}">Asignar</button></div></div><div class="assignment-list">${assignments.length?assignments.map(item=>{const promoter=data.promoters.find(row=>row.id===item.promoter_id);return `<button data-op="edit-assignment" data-id="${shift.id}" data-assignment="${item.id}"><span class="directory-avatar">${esc(promoter?.name?.slice(0,1)||'?')}</span><span><strong>${esc(promoter?.name||'Promotora no disponible')}</strong><small>${assignmentStatuses[item.status]} · ${money(item.rate_cents,item.currency)} / hora</small></span><span aria-hidden="true">Editar</span></button>`;}).join(''):'<p class="hint muted">Sin promotoras asignadas.</p>'}</div></article>`;
 }
 function editShift(shift){
  dirty=false;shell(`<section class="operations detail"><button data-op="detail">← Volver a la activación</button><div class="operations-heading"><div><span class="eyebrow">${esc(current.name)}</span><h2>${shift?'Editar turno':'Añadir turno'}</h2><p class="muted">El fin puede estar en el día siguiente cuando el trabajo termina después de medianoche.</p></div></div><form id="shift-form" class="operations-form compact"><div class="form-grid">${field('Inicio *','starts_at',localValue(shift?.starts_at),'type="datetime-local" required')}${field('Fin *','ends_at',localValue(shift?.ends_at),'type="datetime-local" required')}${field('Promotoras requeridas *','required_people',shift?.required_people||1,'type="number" min="1" max="500" required')}</div><div class="actions"><button class="primary">Guardar turno</button><button type="button" data-op="detail">Cancelar</button></div></form></section>`,'Activaciones');
  const form=document.querySelector('#shift-form');form.oninput=()=>dirty=true;document.querySelector('.operations').onclick=event=>{if(event.target.closest('[data-op=detail]')){if(dirty&&!window.confirm('¿Descartar los cambios sin guardar?'))return;detail(current);}};
  form.onsubmit=async event=>{event.preventDefault();if(busy)return;busy=true;const controls=[...form.elements];controls.forEach(control=>control.disabled=true);try{const saved=await api.saveShift(agency,current.id,shift?.id||crypto.randomUUID(),shift?.revision??null,Object.fromEntries(new FormData(form)));await refresh(current.id);dirty=false;detail(current);notice('Turno guardado.');}catch(error){notice(error.message||'No se pudo guardar el turno.',true);}finally{busy=false;controls.forEach(control=>control.disabled=false);}};
 }
 function editAssignment(shift,item){
  const promoter=data.promoters.find(row=>row.id===item?.promoter_id),available=data.promoters.filter(row=>!row.archived||row.id===item?.promoter_id);
  dirty=false;shell(`<section class="operations detail"><button data-op="detail">← Volver a la activación</button><div class="operations-heading"><div><span class="eyebrow">${shortDate(shift.starts_at)}</span><h2>${item?'Editar asignación':'Asignar promotora'}</h2><p class="muted">${esc(current.name)}</p></div></div><form id="assignment-form" class="operations-form compact"><div class="form-grid"><label>Promotora *<select name="promoter_id" required><option value="">Seleccionar</option>${available.map(row=>`<option value="${row.id}" ${row.id===item?.promoter_id?'selected':''} data-rate="${row.rate_cents??''}" data-currency="${row.currency}">${esc(row.name)} · ${esc(row.city)}</option>`).join('')}</select></label><label>Estado<select name="status">${Object.entries(assignmentStatuses).map(([value,label])=>`<option value="${value}" ${value===(item?.status||'pending')?'selected':''}>${label}</option>`).join('')}</select></label>${field('Tarifa por hora','rate',item?.rate_cents==null?'':(item.rate_cents/100).toFixed(2),'inputmode="decimal" placeholder="Por definir"')}<label>Moneda<select name="currency"><option>USD</option><option>VES</option></select></label></div><small>La tarifa se copia de la ficha al elegir una promotora y puede ajustarse para esta asignación.</small><div class="actions"><button class="primary">Guardar asignación</button><button type="button" data-op="detail">Cancelar</button></div></form></section>`,'Activaciones');
  const form=document.querySelector('#assignment-form');form.elements.currency.value=item?.currency||promoter?.currency||'USD';
  form.elements.promoter_id.onchange=event=>{const option=event.target.selectedOptions[0];if(!option?.value)return;form.elements.rate.value=option.dataset.rate===''?'':(Number(option.dataset.rate)/100).toFixed(2);form.elements.currency.value=option.dataset.currency||'USD';dirty=true;};form.oninput=()=>dirty=true;
  document.querySelector('.operations').onclick=event=>{if(event.target.closest('[data-op=detail]')){if(dirty&&!window.confirm('¿Descartar los cambios sin guardar?'))return;detail(current);}};
  form.onsubmit=async event=>{event.preventDefault();if(busy)return;busy=true;const controls=[...form.elements];controls.forEach(control=>control.disabled=true);try{const values=Object.fromEntries(new FormData(form));const parsed=assignmentPayload(values);const conflict=findScheduleConflict({promoterId:parsed.promoter_id,shiftId:shift.id,startsAt:shift.starts_at,endsAt:shift.ends_at,shifts:data.shifts,assignments:data.assignments.filter(row=>row.id!==item?.id)});if(conflict){const other=data.shifts.find(row=>row.id===conflict.shift_id);throw Error(`Esta promotora ya está asignada a otro turno que se cruza (${shortDate(other.starts_at)}).`);}await api.saveAssignment(agency,shift.id,item?.id||crypto.randomUUID(),item?.revision??null,values);await refresh(current.id);dirty=false;detail(current);notice('Asignación guardada.');}catch(error){notice(error.code==='P0001'?'La promotora ya tiene otro turno en ese horario.':error.message||'No se pudo guardar la asignación.',true);}finally{busy=false;controls.forEach(control=>control.disabled=false);}};
 }
 list();return controller;
}
